development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: qa-factories-training_development
  pool:     5
  username:
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: qa-factories-training_test
  pool:     5
  username:
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: qa-factories-training_production
  pool:     5
  username:
  password: 
  template: template0
