# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c67255f8d25d0a7cd76705879b0cb614708aadf90d91d657783200a14a0b279cff9810fbf3b588208864e79ac4488a21ab5ea893cad8e315821c409ecb9948

test:
  secret_key_base: b5647b3aa4274769d55ce029792237aa2e16295aec7759ae106c864e1647be4a425e8a2c8faf132c05e59c1045d01fbb421f7adacea4ee4a74db7feff677535b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
